site_name: perfpy
site_description: Profiles performance of Python scripts and CLI applications
site_url: https://travishathaway.github.io/perfpy
repo_url: https://github.com/travishathaway/perfpy
repo_name: travishathaway/perfpy

strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
