name: Release Python Package to PyPI

on:
  release:
    types:
      - created

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/perf-for-python
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Build package
        run: |
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1